### ISSUE TITLE
Can't import Ledger

### ISSUE THREAD

**Issue by rqueue** [aionnetwork/Desktop-Wallet#180]
I've followed these instructions https://docs.aion.network/docs/ledger-hardware-wallet-guide to try and import my ledger wallet, but I get an error saying "Cannot connect to Ledger". I enabled *Contract data* and have the Aion app on my ledger open. After pressing the connect button it still shows the same error.

**Comment by centrys-otniel** [comment]
@qoire I've been getting some logs from people encountering this issue and this is mostly caused by the JS integration that we have to go through, though we can't pinpoint the root of the issue. I assume that at some level it's some sort of compatibility problem: 
```18-10-31 12:50:32.119 ERROR WLT  [pool-9-thread-1]: Error wile communicating with the ledger...blue-app-aion@1.0.0
org.aion.wallet.hardware.ledger.LedgerException: Error wile communicating with the ledger...blue-app-aion@1.0.0
	at org.aion.wallet.hardware.ledger.LedgerWallet.getResponse(LedgerWallet.java:198)
	at org.aion.wallet.hardware.ledger.LedgerWallet.getAccountDetails(LedgerWallet.java:123)
	at org.aion.wallet.hardware.ledger.LedgerWallet.isConnected(LedgerWallet.java:106)
	at org.aion.wallet.ui.components.partials.ImportAccountDialog.connectToLedger(ImportAccountDialog.java:316)
	at org.aion.wallet.ui.components.partials.ImportAccountDialog.lambda$radioButtonChanged$1(ImportAccountDialog.java:275)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

Anyway, the fix for this is to create the ledger API in-app. Do you want to hold off the Maintenance release until then?

**Comment by centrys-otniel** [comment]
@rqueue can you please let us know what OS you're using?

**Comment by rqueue** [comment]
I’m using high Sierra. I can check which version specifically later today. I read a reddit pair where someone updated to Mojave and it started to work for them so I was going to try that. Maybe that clue will help some as well

**Comment by rqueue** [comment]
@centrys-otniel I tried updating my OS and am now on Mojave 10.14, but I still get the same `Could not connect to Ledger` error

**Comment by georges** [comment]
The problem still exists on Catalina 10.15.6
